# Generated by Django 5.2.5 on 2025-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('application/octet-stream', 'Application Octet Stream')], default='application/octet-stream', max_length=50),
        ),
    ]
