# Generated by Django 5.2.5 on 2025-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('application/octet-stream', 'Application Octet Stream'), ('video/x-matroska', 'Matroska Video Mkv')], default='application/octet-stream', max_length=50),
        ),
    ]
