# Generated by Django 5.2.5 on 2025-08-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentitem_streaming_alter_contentitem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('application/octet-stream', 'Application Octet Stream'), ('video/mp4', 'Mp4 Video')], default='application/octet-stream', max_length=50),
        ),
    ]
